### ISSUE TITLE
Kodi Jarvis

### ISSUE THREAD

**Issue by Jumblemuddle** [xbmc/visualization.shadertoy#15]
How do I go about building this for Kodi Jarvis?

**Comment by notspiff** [comment]
1) make install on kodi
2) cmake, make, make install
27. feb. 2016 21:48 skrev "Garrett Hopper" <notifications@github.com>:

**Comment by Jumblemuddle** [comment]
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "Findp8-platform.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "p8-platform", but CMake did not find one.

  Could not find a package configuration file provided by "p8-platform" with
  any of the following names:

    p8-platformConfig.cmake
    p8-platform-config.cmake

  Add the installation prefix of "p8-platform" to CMAKE_PREFIX_PATH or set
  "p8-platform_DIR" to a directory containing one of the above files.  If
  "p8-platform" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!

**Comment by notspiff** [comment]
Sorry forgot step 1.5 ; )

Install the dependencies; p8-platform from github.com/PulseEight/platform
and kodi-platform from github.com/xbmc/kodi-platform in that order.
27. feb. 2016 22:18 skrev "Garrett Hopper" <notifications@github.com>:

**Comment by notspiff** [comment]
Missed a dash. It is github.com/Pulse-Eight/platform

**Comment by Jumblemuddle** [comment]
Is this an issue? Should I skip the check?
`sudo cmake .
-- SHADERTOY_VERSION=1.0.6
CMake Error at /usr/lib/kodi/addon-helpers.cmake:128 (message):
  CMAKE_INSTALL_PREFIX /usr/local differs from Kodi prefix /usr.  Please pass
  -DOVERRIDE_PATHS=1 to skip this check
Call Stack (most recent call first):
  CMakeLists.txt:60 (build_addon)`

**Comment by Jumblemuddle** [comment]
Oops, sorry

sudo cmake .
-- SHADERTOY_VERSION=1.0.6
CMake Error at /usr/lib/kodi/addon-helpers.cmake:128 (message):
  CMAKE_INSTALL_PREFIX /usr/local differs from Kodi prefix /usr.  Please pass
  -DOVERRIDE_PATHS=1 to skip this check
Call Stack (most recent call first):
  CMakeLists.txt:60 (build_addon)

**Comment by notspiff** [comment]
give the same prefix for the addon using -DCMAKE_INSTALL_PREFIX=/usr (cmake
parameter)
27. feb. 2016 22:29 skrev "Garrett Hopper" <notifications@github.com>:

**Comment by Jumblemuddle** [comment]
Well, it seems to work. Though I only see a flashing white screen. How can I change the shader? The settings for the visulizer just shows a 'General' entry which I can't click on.

**Comment by notspiff** [comment]
You use the preset selection dislog, far right in confluence music osd
27. feb. 2016 22:34 skrev "Garrett Hopper" <notifications@github.com>:

**Comment by Jumblemuddle** [comment]
Well, there's one problem, I'm not using confluence.
I switched to confluence to test this. All the presets appear as strange symbols (@, p5, #*, @, PQb, #*, #*, #*, PQb) (* stands for the unknown x thing) If I select any of them, I still just get a flashing white screen.

**Comment by Jumblemuddle** [comment]
Upon restarting kodi, I get this:
http://imgur.com/1rEWFvg

**Comment by notspiff** [comment]
Weird, i have never seen that behavior. Log reveal anything? Currently on
vacation with my phone as the only puter so limited investigation options..
27. feb. 2016 22:41 skrev "Garrett Hopper" <notifications@github.com>:

**Comment by Jumblemuddle** [comment]
Nothing in the log. :/
I totally understand. Please don't let me take too much of your time.

**Comment by notspiff** [comment]
No worries if it was annoying me i would simply ignore;) i dont know what
to suggest but i will investigate and get back to you in a few days when i
get back home.
27. feb. 2016 22:46 skrev "Garrett Hopper" <notifications@github.com>:

**Comment by Jumblemuddle** [comment]
Alright, I'll let you know if I find anything useful. Thanks for your help!

**Comment by AngryUbuntuNerd** [comment]
I can confirm the appearance of weird characters, but not the crash screen. Nothing else than a flashing white screen. Using the kodi-visualizer-shadertoy package from the official Kodi repository. Any ideas what might be the problem?

**Comment by notspiff** [comment]
not really. i have heard others say it doesn't play nicely with intel drivers, but i have nowhere to test such a configuration.

**Comment by notspiff** [comment]
i did find one nasty issue right now, https://github.com/notspiff/visualization.shadertoy/commit/a178dc896d4705191e44beeccbb5e156a1d210e3 it could potentially have caused random behavior.

**Comment by notspiff** [comment]
think i found it. when the gl and gles versions were merged, we ended up with gles precision directives in gl shaders. the nvidia driver is too helpful, it silently ignores those directives in gl shaders. with mesa, not so much.

**Comment by AlwinEsch** [comment]
Think is no longer active.
