### ISSUE TITLE
Problems with LibreElec and Shadertoy

### ISSUE THREAD

**Issue by pike2k** [xbmc/visualization.shadertoy#18]
Hello old friend.

I coaxed milhouse to include Shadertoy with their fork of OpenElec -> LibreElec.
Sadly it doesn't function properly. Do you know what special requirements this vis might have to work with LibreElec? I am using https://libreelec.tv/2016/06/libreelec-krypton-v7-90-002-alpha/ on Intel gfx.

**Comment by notspiff** [comment]
hi there.

there should be very small requirement for this to run, opengl and glew. however, intel gfx might be an issue depending on version. this is pure shaders and old intel gfx is limited in what shaders is supported. that being said, some of the presets even work with the mesa software renderer so that everything is borked due to intel gfx seems unlikely.

when you say don't work, do you mean black screen but you get the preset list etc, or does it fail to load? if it is the latter, a debug log shall disclose the why.

**Comment by pike2k** [comment]
With some presets, screen is black, usually though it's gray, looks like a faint pulsing when it's gray. I can't even be certain that the preset toggling has any effect. :palm_tree: 
[kodi.160623_.log.txt](https://github.com/notspiff/visualization.shadertoy/files/330507/kodi.160623_.log.txt)

**Comment by thielj** [comment]
The popcornmix version here (v1.0.8) is working:
  https://github.com/popcornmix/repository.popcornmix.storage/tree/master/visualization.shadertoy
 
LibreElec's own version (derived from an earlier v1.0.6?) was bumped to v1.1 and auto-updates over the above, so make sure you disable automatic updates.

**Comment by akva2** [comment]
in that case i probably screwed up something while unifying the 3 different versions peeps had managed to create... (one for gl, one for dx, one for gles). judging by the version number it seems @popcornmix kept his version alive for some reason ?

**Comment by popcornmix** [comment]
Note GL and GLES versions need compile time changes, so different .so files.
Do we have a means of supporting GL linux and GLES linux from the same repo?
That was the obstacle for merging them a while back.
You can't specify the platform needs GL vs GLES (unless you know of a way?)

**Comment by akva2** [comment]
on build time yes, on install time no. linux repos are intended to be supplied by platform tools (apt et al). the idea was always to have one repo per arch, backed by a native repo (apt or the likes) for relevant platforms, or zip files for the rest. but all of that stalled when i left. the hook was even taken out of the repo handling code so i have no idea what plans you guys have for it now.

**Comment by notspiff** [comment]
please try HEAD.

**Comment by akva2** [comment]
millhouse included an updated add-on in today's build (see http://forum.kodi.tv/showthread.php?tid=269815&pid=2448672#pid2448672 and post after it)

**Comment by AlwinEsch** [comment]
Due to the age of this issue, it is closed for the time being.
