### ISSUE TITLE
Question for compile

### ISSUE THREAD

**Issue by hawkeyexp** [xbmc/visualization.shadertoy#22]
Sorry to use this way but no other solution found and no contact via email etc...

i managed to compile full build of kodi on pi3 - all works fine but visualization stay black - i think cause gl and gles but how can i specify to use correct one on compile time ?

I used this way (default on pvr addons)

    git clone https://github.com/xbmc/xbmc.git
    git clone https://github.com/kodi-pvr/pvr.hts.git
    cd pvr.hts && mkdir build && cd build
    cmake -DADDONS_TO_BUILD=pvr.hts -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
    make

Thx !

**Comment by akva2** [comment]
There has been no use for a switch thus far so if it doesnt pick gles for you, you have to fiddle cmakelists.txt yourself.

**Comment by akva2** [comment]
Repo owner in work clothes

**Comment by hawkeyexp** [comment]
Today tried a lot of things but no luck :-( No ideas?

**Comment by dimmuboy** [comment]
I tried this
```
git clone https://github.com/xbmc/kodi-platform.git
git clone https://github.com/notspiff/visualization.shadertoy.git
mkdir visualization.shadertoy/build && cd visualization.shadertoy/build
cp xbmc/xbmc/addons/kodi-addon-dev-kit/include/kodi visualization.shadertoy/build/
cmake -DCMAKE_BUILD_TYPE=Debug -DPACKAGE_ZIP=1 ../
make
```

In visualization.shadertoy/src/main.cpp:21:11 I must put full path but after make I got warning and my addon doesn't working.
```
[ 20%] Building C object lib/kissfft/CMakeFiles/kissfft.dir/kiss_fft.c.o
[ 40%] Linking C static library libkissfft.a
[ 40%] Built target kissfft
[ 60%] Building CXX object CMakeFiles/visualization.shadertoy.dir/src/lodepng.cpp.o
[ 80%] Building CXX object CMakeFiles/visualization.shadertoy.dir/src/main.cpp.o
/home/osmc/visualization.shadertoy/src/main.cpp:715:7: warning: 'CVisualizationShadertoy' declared with greater visibility than the type of its field 'CVisualizationShadertoy::<anonymous>' [-Wattributes]
 class CVisualizationShadertoy
       ^~~~~~~~~~~~~~~~~~~~~~~
/home/osmc/visualization.shadertoy/src/main.cpp:715:7: warning: 'CVisualizationShadertoy' declared with greater visibility than its base 'kodi::addon::CAddonBase' [-Wattributes]
[100%] Linking CXX shared library visualization.shadertoy.so
[100%] Built target visualization.shadertoy
```

**Comment by notspiff** [comment]
it works fine for me. with so little information provided on how you concluded it doesn't work, that's the best i can do. logs, what steps did you take to include it in your kodi, which platform, etc etc.

the warning is harmless.

**Comment by dimmuboy** [comment]
I'm running on latest OSMC distro.
Kodi 17.6
Debian Stretch 9.3

here is log of compiling
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking to see if CXX compiler accepts flag -flto
-- Checking to see if CXX compiler accepts flag -flto - yes
-- Found OpenGL: /usr/lib/arm-linux-gnueabihf/libGL.so  
-- SHADERTOY_VERSION=1.1.8
-- Configuring done
-- Generating done
-- Build files have been written to: /home/osmc/visualization.shadertoy/build

```
Make log was above.

**Comment by notspiff** [comment]
okay, so we are running with opengl. now i need log on *kodi* side of things. where it tries to load the add-on etc.

**Comment by dimmuboy** [comment]
Sorry for late answer. It looks like some problem with compiled library
```
20:25:35.049 T:1925581312 WARNING: Unable to resolve: /visualization.shadertoy.so.1.1.8 ADDON_Stop, reason: /home/osmc/.kodi/addons/visualization.shadertoy/visualization.shadertoy.so.1.1.8: undefined symbol: ADDON_Stop
20:25:35.049 T:1925581312   ERROR: Unable to resolve exports from dll /home/osmc/.kodi/addons/visualization.shadertoy/visualization.shadertoy.so.1.1.8
20:25:35.103 T:1925581312 WARNING: Unable to resolve: /visualization.shadertoy.so.1.1.8 ADDON_Stop, reason: /home/osmc/.kodi/addons/visualization.shadertoy/visualization.shadertoy.so.1.1.8: undefined symbol: ADDON_Stop
20:25:35.104 T:1925581312   ERROR: Unable to resolve exports from dll /home/osmc/.kodi/addons/visualization.shadertoy/visualization.shadertoy.so.1.1.8
```
I'm using Raspberry Pi 3.

**Comment by notspiff** [comment]
Exactly what it would look like if u tried master with 17.6. Did u build
the tag?

31. jan. 2018 20:33 skrev "DimmuBoy" <notifications@github.com>:

**Comment by dimmuboy** [comment]
What you mean with that tag?

**Comment by notspiff** [comment]
as i wrote above you cannot build HEAD against kodi 17.6, you have to use the latest tag, https://github.com/notspiff/visualization.shadertoy/releases/tag/v1.1.5

**Comment by circulosmeos** [comment]
@dimmuboy :
You need to download Kodi repo, select the Kodi 17 branch, and then download this repo and do the same. As [I've just done this very same process](https://github.com/circulosmeos/visualization.shadertoy) here are the commands:

1. `git clone https://github.com/xbmc/xbmc.git`
2. `cd xbmc && git checkout tags/17.6-Krypton && cd ..`
3. `git clone https://github.com/xbmc/visualization.shadertoy.git`
4. `cd visualization.shadertoy && git checkout v1.1.5 && mkdir build && cd build`
5. **read NOTE**
6. `cmake -DADDONS_TO_BUILD=visualization.shadertoy -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/kodi-build/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons`
7. `make`
8. `cd ../../xbmc/kodi-build/addons && strip visualization.shadertoy/visualization.shadertoy.so.1.1.5`
9. `zip -r --symlinks visualization.shadertoy-1.1.5.zip visualization.shadertoy/`

This zip is directly installable from Kodi.

**NOTE:**
Please, note that at least for the device ODROID-C2 with Ubuntu 16.04, v1.1.5 did not correctly linked with GLESv2 libraries (for the embedded GPU), which made the addon show nothing.
So, modify your `visualization.shadertoy/CMakeLists.txt` like [this one](https://github.com/circulosmeos/visualization.shadertoy/blob/odroid-c2/CMakeLists.txt) to patch it, and continue from step 5.

**Comment by dimmuboy** [comment]
It's work with latest version but it shows another error for now.
I use commands from main README and after make I do strip and zip with command above (only version was changed to current)

```
ERROR: AddOnLog: Shadertoy: CShaderProgram::CompileAndLink: ERROR:CUSTOM-28 (vertex shader, line 1) Incorrect #version
ERROR: AddOnLog: Shadertoy: Failed to compile shadertoy shaders (current shadertoy file '/home/osmc/.kodi/addons/visualization.shadertoy/resources/shaders/main_test.frag.glsl')
ERROR: AddOnLog: Shadertoy: CShaderProgram::CompileAndLink: ERROR:CUSTOM-28 (vertex shader, line 1) Incorrect #version
ERROR: AddOnLog: Shadertoy: Failed to compile shadertoy shaders (current shadertoy file '/home/osmc/.kodi/addons/visualization.shadertoy/resources/shaders/bpm.frag.glsl')
ERROR: AddOnLog: Shadertoy: CShaderProgram::CompileAndLink: ERROR:CUSTOM-28 (vertex shader, line 1) Incorrect #version
ERROR: AddOnLog: Shadertoy: Failed to compile shadertoy shaders (current shadertoy file '/home/osmc/.kodi/addons/visualization.shadertoy/resources/shaders/bpm.frag.glsl')
ERROR: AddOnLog: Shadertoy: CShaderProgram::CompileAndLink: ERROR:CUSTOM-28 (vertex shader, line 1) Incorrect #version
ERROR: AddOnLog: Shadertoy: Failed to compile shadertoy shaders (current shadertoy file '/home/osmc/.kodi/addons/visualization.shadertoy/resources/shaders/bpm.frag.glsl')
ERROR: AddOnLog: Shadertoy: CShaderProgram::CompileAndLink: ERROR:CUSTso threadOM-28 (vertex shader, line 1) Incorrect #version
ERROR: AddOnLog: Shadertoy: Failed to compile shadertoy shaders (current shadertoy file 
```

//EDIT: However v1.1.10 by Team Kodi repo works great on 1920x1080i. With 1920x1080p are some visualizations misaligned (left and bottom margin).
//EDIT2: problem with margins appears after display calibration no resolution changing

**Comment by AlwinEsch** [comment]
Can you give a kodi.log (upload e.g. to https://paste.kodi.tv/) to see which GPU Hardware is used, your error is not related to addon compile, is about the Shader code which is created on every Visualization start.

**Comment by dimmuboy** [comment]
I'm okay with version from official kodi repo now.  I have only problem with misalignment so this thread can be closed I will open new one.
Thank you for your patience :)
