### ISSUE TITLE
Not an issue: are there demo videos around

### ISSUE THREAD

**Issue by JulienMaille** [xbmc/visualization.shadertoy#32]
Sorry to hijack the issues system, but I'm currently not using Kodi and was wondering if there are any videos showing nice shaders running on your plugin?
Thanks in advance

**Comment by dimmuboy** [comment]
All shaders are available on https://www.shadertoy.com/
Each shader (in `/visualization.shadertoy/resources`) contains url reference to specific shader so you can see how will it look 
e.g. https://github.com/xbmc/visualization.shadertoy/blob/Leia/visualization.shadertoy/resources/2Dspectrum.frag.glsl
