### ISSUE TITLE
shadertoy doesn't work on Kodi Leia Beta 5 x64 for Windows

### ISSUE THREAD

**Issue by amatesi** [xbmc/visualization.shadertoy#33]
Hi and thank you for this addon.

There seems to be an issue with your addon on Kodi Leia Beta 5 x64 for Windows.

This has been confirmed by 3xistence and me on the kodi forums - https://forum.kodi.tv/showthread.php?tid=336793

Thanks.

Regards,
Andrea.

**Comment by MarkCallow** [comment]
It still doesn’t work on Kodi Leia RC3. Do I Need to download a new version from somewhere? I can’t find anything in the Kodi add-on repo. Please fix.

**Comment by MarkCallow** [comment]
Still unavailable in Kodi Leia RC5.2.

Is shadertoy visualization going to be fixed? Is it available in another add-ons repo?

**Comment by Rechi** [comment]
@MarkCallow please properly describe what's your issue. Also mention how to reproduce and include the kodi log with debugging enabled.

**Comment by MarkCallow** [comment]
When I installed Kodi 18, I still had shadertoy installed from Kodi 17.6. It did not run. There was no visualization even though shadertoy was still set as the visualization. I looked for shadertoy in the official Kodi add-ons repo and could not find it. Only ProjectM and Spectrum appeared under Visualization. That was when I filed my first message. I gave up on shadertoy and switched to ProjectM.

Due to unrelated issues, I had to create a new profile for Kodi 18 which, of course, lacks the shadertoy add-on. Today I again looked in the add-ons repo for Kodi 18 and still only ProjectM and Spectrum appear.

How to I install this add-on if it is not found in the official Kodi add-ons repo? This is problem #1.

**Comment by Rechi** [comment]
So you actually do not run Windows, like the issue title states?

**Comment by MarkCallow** [comment]
Oops!. Sorry I didn't notice that part of the title. I am running on macOS.

**Comment by MarkCallow** [comment]
Is the add-on available for macOS?

**Comment by hewwra** [comment]
Here is a [log](http://paste.kodi.tv/lesabunata).
There is no visualization displayed on my screen, just a black background.

**Comment by tmortonorr** [comment]
Confirmed here too, I'm running Kodi 18.0 Release on Windows 10 64bit and shadertoy doesn't work. No visualisations show up which is a shame since shadertoy has the better visualisations.

**Comment by mwheinz** [comment]
So, I'm having a similar problem with shadertoy on libreelec running on a raspi 3B. Behavior is that the visualizer works when activated but when the track advances, or if I switch to a different window, the visualizer goes blank and never seems to recover. I didn't notice anything in the logs to indicate a problem.

It's a pity because shadertoy is so much better than the other visualizers.

**Comment by tmortonorr** [comment]
I've installed 32 bit Windows version of Kodi and get the same problem, no visualisations appear. Can the developer confirm if this is a problem being looked into?

**Comment by mwheinz** [comment]
So, one thing to check - I accidentally discovered that when I changed my Kodi skin from Estuary to Eminence, shadertoy started working - but I haven't really dug into it. It might be interesting to do a similar test in your own environment?

**Comment by tmortonorr** [comment]
@mwheinz what is your environment? I just tried using Eminence but it still doesn't work. Shadertoy works fine on my Android installations just not Windows.

**Comment by mwheinz** [comment]
@tmortonorr - as I mentioned in my previous comment, I'm using libreelec.tv on a Raspberry Pi 3b - so Linux running the current release of Kodi.

**Comment by Rechi** [comment]
@amatesi @hewwra @tmortonorr download the correct zip file at https://jenkins.kodi.tv/view/Addons/job/xbmc/job/visualization.shadertoy/view/change-requests/job/PR-36/ and install from ZIP inside Kodi.
Does it work?

**Comment by tmortonorr** [comment]
@Rechi I can confirm that the zip file update fixes the issue on Windows x64 using the latest release of Kodi v18.1

Thanks for your hard work!

**Comment by hewwra** [comment]
I does not work for me, I run Windows x64 and 32-bit Kodi 18.1.
It does not even install for me.
[Log](http://paste.kodi.tv/esutiyetij)

**Comment by Rechi** [comment]
@hewwra are you trying to install the correct zip file for your platform (windows-i686)?

**Comment by hewwra** [comment]
So I tried the i686 instead and the install worked however shadertoy does not work, it crashes both Kodi and Windows. Do you need the dmp file as well?

[Log](https://paste.kodi.tv/felamuvoji.kodi)

**Comment by Rechi** [comment]
@hewwra I need a log file with debug logging enabled from the beginning (https://kodi.wiki/view/Log_file). Please also share the dmp file.

**Comment by hewwra** [comment]
Here is the [log](https://www.dropbox.com/s/bvgnd22mj40jbfc/Kodi_Shadertoy_20190322.zip?dl=0) file

**Comment by Rechi** [comment]
@hewwra please try again with [visualization.shadertoy-1.1.9.zip](https://github.com/xbmc/visualization.shadertoy/files/3000138/visualization.shadertoy-1.1.9.zip) and post the dmp file again. Maybe it gives more info what causes the crash.

**Comment by hewwra** [comment]
I installed the zip-file again but it refused to start the visualization, it said some unknown error had occurred.
[Log](https://paste.kodi.tv/odehesiniz.kodi)

**Comment by Rechi** [comment]
Please try again with [visualization.shadertoy-1.1.9.zip](https://github.com/xbmc/visualization.shadertoy/files/3000250/visualization.shadertoy-1.1.9.zip).

**Comment by hewwra** [comment]
Alright, here is the log
[Kodi_Shadertoy_20190324.zip](https://github.com/xbmc/visualization.shadertoy/files/3000329/Kodi_Shadertoy_20190324.zip)

**Comment by Rechi** [comment]
@hewwra I've no idea what causes the crash. Maybe @afedchin can have a look at it.

**Comment by afedchin** [comment]
the addon will be re-written completely for matrix
