### ISSUE TITLE
LibreELEC 9.0.1 Shadertoy (1.1.9.1) just shows a blank screen

### ISSUE THREAD

**Issue by fpoto** [xbmc/visualization.shadertoy#37]
Just upgraded to 9.0.1 from Libreelec 8, and Shadertoy works no more.

When the screensaver kicks in, I get a blank screen.
Even starting from the configuration and selecting preview I get a blank screen (tried with Random, Ball and a couple more).
Other screensavers work, I tried Aerial, Kaster and Google earth.

**Comment by fpoto** [comment]
Well, please close this bug. It started working on its own...

**Comment by AlwinEsch** [comment]
You reported right for this addon, if the system use GL3 this can ot work :smile: 
Becomes fixed with https://github.com/xbmc/visualization.shadertoy/pull/43

**Comment by fpoto** [comment]
>You reported right for this addon, if the system use GL3 this can ot work :smile: 
>Becomes fixed with https://github.com/xbmc/visualization.shadertoy/pull/43

Not at home right now, so I cannot check this, but my report was based
on obaserved behaviour on Raspberry, no idea if that uses GL.

Thanks for your work!
